name: Build & Publish Debian Package

on:
  schedule:
    - cron: "54 7 * * *"
  push:
    branches:
      - main

jobs:
  build-and-publish:
    environment: Main
    runs-on: ubuntu-latest
    env:
      DISTRIBUTION: any
      COMPONENT: main
      ARCHITECTURE: amd64
      RELEASE: 1
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      KEY_ID: ${{ vars.KEY_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y reprepro dpkg-dev curl jq gnupg debsigs

      - name: Determine latest uv version
        id: get-version
        run: |
          TAG=$(curl -s https://api.github.com/repos/astral-sh/uv/releases/latest | jq -r '.tag_name')
          VERSION=${TAG#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "$KEY_ID:6:" |  gpg --batch --import-ownertrust --pinentry-mode=loopback

      - name: Download latest uv binary
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/astral-sh/uv/releases/latest | jq -r '.assets[] | select(.name | contains("x86_64-unknown-linux-gnu")) | select(.name | endswith(".tar.gz")) | .browser_download_url')
          curl -L "$DOWNLOAD_URL" -o uv.tar.gz
          mkdir dl
          tar xf uv.tar.gz -C dl

      - name: Build Debian package
        run: |
          PKG_VERSION="${{ steps.get-version.outputs.version }}-$RELEASE"
          PKG="uv_${PKG_VERSION}_${ARCHITECTURE}.deb"
          mkdir -p pkg/DEBIAN pkg/usr/bin
          echo "Package: uv" >pkg/DEBIAN/control
          echo "Version: ${PKG_VERSION}" >>pkg/DEBIAN/control
          echo "Section: utils" >>pkg/DEBIAN/control
          echo "Priority: optional" >>pkg/DEBIAN/control
          echo "Architecture: ${ARCHITECTURE}" >>pkg/DEBIAN/control
          echo "Maintainer: GitHub Actions <actions@github.com>" >>pkg/DEBIAN/control
          echo "Description: UV CLI binary" >>pkg/DEBIAN/control
          fakeroot bash -c "install -o root -g root -m 755 dl/*/uv* pkg/usr/bin ; dpkg-deb --build pkg $PKG"

      - name: Sign Debian package
        run: |
          debsigs -v --gpgopts="--batch --no-tty --pinentry-mode=loopback" --sign=origin --default-key="$KEY_ID" uv*.deb

      - name: Create APT repository with reprepro
        run: |
          mkdir -p repo/conf
          echo "Origin: GitHub" >repo/conf/distributions
          echo "Label: GitHub UV" >>repo/conf/distributions
          echo "Suite: stable" >>repo/conf/distributions
          echo "Codename: ${DISTRIBUTION}" >>repo/conf/distributions
          echo "Components: ${COMPONENT}" >>repo/conf/distributions
          echo "Architectures: ${ARCHITECTURE}" >>repo/conf/distributions
          echo "SignWith: $KEY_ID" >>repo/conf/distributions
          reprepro -Vb repo includedeb ${DISTRIBUTION} "uv_${{ steps.get-version.outputs.version }}-${RELEASE}_${ARCHITECTURE}.deb"
          cp uvrepo-public.gpg repo/pubkey.gpg
          cp index.html repo/

      - name: Deploy APT repository to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
